# This cpawd configuration runs the PythonUtils testing framework

include:
  - projectDirs.yaml

tasks:

  natsServer:
    runOnce: true
    env:
      NATS_SERVER : "nats://{natsServer[host]}:{natsServer[port]}"
    cmd:
      - echo
      - "Using nats server at:"
      - "{natsServer[host]}:{natsServer[port]}"

  natsListener:
    runOnce: true
    cmd:
      - cplogger
      - -v
      - -P
      - "{natsServer[port]}"
      - -H
      - "{natsServer[host]}"

  generateInterface:
    watch:
      - interfaces
    cmd:
      - cpig
      - All.md

  cpInterfaces:
    watch:
      - "{generateInterface[projectDir]}/interfaces"
    cmd:
      - cp
      - -R
      - "{generateInterface[projectDir]}/dist/python/"
      - "{cpInterfaces[projectDir]}/interfaces"

  pythonUtilsTests:
    watch:
      - tests
      - cputils
      - examples
      - interfaces
    cmd:
      - python
      - -W
      - "ignore::DeprecationWarning"
      - -m
      - unittest
      - discover
      - -v
      - .
      - -p
      - '*_tests.py'
